# Generated by Django 5.0.4 on 2024-04-27 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferramentas', '0007_ferramenta_saida_delete_ferramentaestoque'),
        ('funcionario', '0002_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('entregue', models.BooleanField(default=False)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferramentas.ferramenta')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
            ],
        ),
    ]
