# Generated by Django 5.0.4 on 2024-04-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsaida',
            name='entregue',
        ),
    ]
