# Generated by Django 5.0.4 on 2024-04-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_logsaida_entregue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferramenta', models.CharField(max_length=200)),
                ('funcionario', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateTimeField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('LogSaida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.logsaida')),
            ],
        ),
    ]
