# Generated by Django 5.0.4 on 2024-04-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_logentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentrada',
            name='data',
        ),
        migrations.RemoveField(
            model_name='logentrada',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='logentrada',
            name='ferramenta',
        ),
        migrations.RemoveField(
            model_name='logentrada',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='logentrada',
            name='quantidade',
        ),
    ]
