# Generated by Django 5.0.4 on 2024-04-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_logentrada_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentrada',
            name='data',
        ),
    ]
