# Generated by Django 5.0.4 on 2024-04-27 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_logentrada_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentrada',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logentrada',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logentrada',
            name='ferramenta',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logentrada',
            name='funcionario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='logentrada',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
