# Generated by Django 5.0.4 on 2024-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_remove_logentrada_data_remove_logentrada_data_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsaida',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
    ]
