# Generated by Django 5.0.4 on 2024-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rotulo', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('estoque', models.IntegerField()),
                ('saida', models.IntegerField()),
            ],
        ),
    ]
