# Generated by Django 5.0.4 on 2024-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_rename_rotulo_ferramenta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='saida',
            field=models.IntegerField(default=0),
        ),
    ]
