# Generated by Django 5.0.4 on 2024-04-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0003_alter_ferramenta_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='saida',
        ),
    ]
