# Generated by Django 5.0.4 on 2024-04-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0004_remove_ferramenta_estoque_remove_ferramenta_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='FerramentaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.IntegerField(default=0)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferramentas.ferramenta', to_field='codigo')),
            ],
        ),
    ]
