# Generated by Django 5.0.4 on 2024-04-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0005_alter_ferramenta_codigo_ferramentaestoque'),
        ('funcionario', '0002_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentaestoque',
            name='funcionario',
            field=models.ForeignKey(default='00000000000', on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', to_field='cpf'),
        ),
    ]
