# Generated by Django 5.0.4 on 2024-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0006_ferramentaestoque_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='saida',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FerramentaEstoque',
        ),
    ]
